export { default as NextUILogo } from '@/components/TechIcons/NextUILogo'
export { default as NextjsLogo } from '@/components/TechIcons/NextjsLogo'
export { default as ReactLogo } from '@/components/TechIcons/ReactLogo'
export { default as ShadcnuiLogo } from '@/components/TechIcons/ShadcnuiLogo'
export { default as TailwindcssLogo } from '@/components/TechIcons/TailwindcssLogo'
export { default as TypeScriptLogo } from '@/components/TechIcons/TypeScriptLogo'
export { default as ZustandLogo } from '@/components/TechIcons/ZustandLogo'
export { default as MotionLogo } from '@/components/TechIcons/MotionLogo'
